### ISSUE TITLE
Environment variables for FTP and SFTP are same

### ISSUE THREAD

**Issue by Wandermond** [beaukode/docker-cron-backup#3]
Hi! I have just noticed that you use the same variables for FTP and SFTP backup variants in your `start.sh`. So, you have the same host/port/path/user/password for FTP and SFTP connections. I think this is the issue and it should be fixed.

// Part of `start.sh` with `env.sh` creating
echo "
export BACKUP_SOURCE=$BACKUP_SOURCE
export FTP_HOST=$FTP_HOST
export FTP_PORT=$FTP_PORT
export FTP_PATH=$FTP_PATH
export FTP_USERNAME=$FTP_USERNAME
export FTP_PASSWORD=$FTP_PASSWORD
**export SFTP_HOST=$FTP_HOST
export SFTP_PORT=$FTP_PORT
export SFTP_PATH=$FTP_PATH
export SFTP_USERNAME=$FTP_USERNAME
export SFTP_PASSWORD=$FTP_PASSWORD**
export SFTP_PRIVKEY=$SFTP_PRIVKEY
export OS_AUTH_URL=$OS_AUTH_URL
export OS_USERNAME=$OS_USERNAME
export OS_PASSWORD=$OS_PASSWORD
export OS_PROJECT_NAME=$OS_PROJECT_NAME
export OS_REGION_NAME=$OS_REGION_NAME
export OS_DELETE_AFTER=$OS_DELETE_AFTER
export OS_CONTAINER=$OS_CONTAINER
export OS_PATH=$OS_PATH
" > /env.sh

**Comment by beaukode** [comment]
You are right, this is fixed and added some tests in new release https://github.com/beaukode/docker-cron-backup/tree/1.1
